//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOD
    {
        public string Id { get; set; }
        public string ProductId { get; set; }
        public Nullable<decimal> TotalAmont { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public Nullable<System.DateTime> ModfiedDate { get; set; }
        public string MySoId { get; set; }
        public Nullable<decimal> QTY { get; set; }
    
        public virtual MySO MySO { get; set; }
        public virtual Product Product { get; set; }
    }
}
